[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 200
maxMessageSize = 200
enableXsrfProtection = true
enableCORS = false
runOnSave = true

[client]
toolbarMode = "minimal"
showErrorDetails = false

[browser]
serverAddress = "streamlit.app"
gatherUsageStats = false